/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package skyproc;

/**
 *
 * @author Justin Swanson
 */
public enum ActorValue {

    Aggression,
    Confidence,
    Energy,
    Morality,
    Mood,
    Assistance,
    OneHanded,
    TwoHanded,
    Marksman,
    Block,
    Smithing,
    HeavyArmor,
    LightArmor,
    Pickpocket,
    Lockpicking,
    Sneak,
    Alchemy,
    Speechcraft,
    Alteration,
    Conjuration,
    Destruction,
    Illusion,
    Restoration,
    Enchanting,
    Health,
    Magicka,
    Stamina,
    HealRate,
    MagickaRate,
    StaminaRate,
    SpeedMult,
    InventoryWeight,
    CarryWeight,
    DragonRend,
    CritChance,
    MeleeDamage,
    UnarmedDamage,
    Mass,
    VoicePoints,
    VoiceRate,
    DamageResist,
    PoisonResist,
    FireResist,
    ElectricResist,
    FrostResist,
    MagicResist,
    DiseaseResist,
    Paralysis,
    Invisibility,
    NightEye,
    DetectLifeRange,
    WaterBreathing,
    WaterWalking,
    IgnoreCrippledLimbs,
    Fame,
    Infamy,
    JumpingBonus,
    WardPower,
    RightItemCharge,
    LeftItemCharge,
    EquippedItemCharge,
    ArmorPerks,
    ShieldPerks,
    Variable01,
    Variable02,
    Variable03,
    Variable04,
    Variable05,
    Variable06,
    Variable07,
    Variable08,
    Variable09,
    Variable10,
    FavorActive,
    FavorsPerDay,
    FavorsPerDayTimer,
    EquippedStaffCharge,
    AbsorbChance,
    Blindness,
    WeaponSpeedMult,
    ShoutRecoveryMult,
    BowStaggerBonus,
    Telekinesis,
    FavorPointsBonus,
    LastBribedIntimidated,
    LastFlattered,
    MovementNoiseMult,
    BypassVendorStolenCheck,
    BypassVendorKeywordCheck,
    WaitingForPlayer,
    OneHandedMod,
    TwoHandedMod,
    MarksmanMod,
    BlockMod,
    SmithingMod,
    HeavyArmorMod,
    LightArmorMod,
    PickPocketMod,
    LockpickingMod,
    SneakMod,
    AlchemyMod,
    SpeechcraftMod,
    AlterationMod,
    ConjurationMod,
    DestructionMod,
    IllusionMod,
    RestorationMod,
    EnchantingMod,
    OneHandedSkillAdvance,
    TwoHandedSkillAdvance,
    MarksmanSkillAdvance,
    BlockSkillAdvance,
    SmithingSkillAdvance,
    HeavyArmorSkillAdvance,
    LightArmorSkillAdvance,
    PickPocketSkillAdvance,
    LockpickingSkillAdvance,
    SneakSkillAdvance,
    AlchemySkillAdvance,
    SpeechcraftSkillAdvance,
    AlterationSkillAdvance,
    ConjurationSkillAdvance,
    DestructionSkillAdvance,
    IllusionSkillAdvance,
    RestorationSkillAdvance,
    EnchantingSkillAdvance,
    LeftWeaponSpeedMult,
    DragonSouls,
    CombatHealthRegenMult,
    OneHandedPowerMod,
    TwoHandedPowerMod,
    MarksmanPowerMod,
    BlockPowerMod,
    SmithingPowerMod,
    HeavyArmorPowerMod,
    LightArmorPowerMod,
    PickPocketPowerMod,
    LockpickingPowerMod,
    SneakPowerMod,
    AlchemyPowerMod,
    SpeechcraftPowerMod,
    AlterationPowerMod,
    ConjurationPowerMod,
    DestructionPowerMod,
    IllusionPowerMod,
    RestorationPowerMod,
    EnchantingPowerMod,
    AttackDamageMult,
    HealRateMult,
    MagickaRateMult,
    StaminaRateMult,
    CombatHealthRegenMultMod,
    CombatHealthRegenMultPowerMod,
    HealRatePowerMod,
    MagickaRateMod,
    ReflectDamage,
    NormalWeaponsResist,
    PerceptionCondition,
    EnduranceCondition,
    LeftAttackCondition,
    RightAttackCondition,
    LeftMobilityCondition,
    RightMobilityCondition,
    BrainCondition,
    UNKNOWN;

    static int value(ActorValue in) {
	if (in == UNKNOWN) {
	    return -1;
	} else {
	    return in.ordinal();
	}
    }

    static ActorValue value(int in) {
	if (in < ActorValue.values().length - 2 && in >= 0) {
	    return ActorValue.values()[in];
	} else {
	    return UNKNOWN;
	}
    }
}
