/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package skyproc;

import java.io.*;
import java.util.ArrayList;
import java.util.Scanner;

/**
 *
 * @author Justin Swanson
 */
class EmbeddedScripts {

    // Highly specific function meant to parse the function list from
    // mod.gib.me/skyrim/functions.html as an easier way to generate
    // script objects, rather than typing it all by hand.
    // Shouldn't need to be used by you or any users.
    static void parseScriptData() throws FileNotFoundException, IOException {
	String dir = "Validation Files/";
	BufferedReader in = new BufferedReader(new FileReader(dir + "EmbeddedScriptSource.txt"));
	BufferedWriter out = new BufferedWriter(new FileWriter(dir + "EmbeddedScriptOut.txt"));
	BufferedWriter log = new BufferedWriter(new FileWriter(dir + "EmbeddedScriptOutLog.txt"));
	ArrayList<String> enumStrings = new ArrayList<>();
	int curIndex = -1;
	while (in.ready()) {
	    String line = in.readLine();
	    log.write("Read Line: " + line + "\n");
	    Scanner tokenizer = new Scanner(line);
	    try {
		int index = Integer.valueOf(tokenizer.next());
		log.write("  Index: " + index + "\n");
		if (index < 4096) {
		    log.write("  Skipped.\n");
		    continue;
		} else {
		    index -= 4096;
		}
		String name = tokenizer.next();
		if (name.contains("ref.")) {
		    name = tokenizer.next();
		}
		log.write("  Ref: " + name + "\n");
		ArrayList<Boolean> parameterMask = new ArrayList<Boolean>();
		tokenizer.useDelimiter(",");
		while (tokenizer.hasNext()) {
		    String parameter = tokenizer.next();
		    if (parameter.contains("UNK")) {
			parameterMask.add(true);
			log.write("  Parameter " + parameter + " TRUE\n");
		    } else {
			parameterMask.add(false);
			log.write("  Parameter " + parameter + " FALSE\n");
		    }
		}

		// Generate string
		String enumString = name + " (";
		boolean first = true;
		for (Boolean b : parameterMask) {
		    if (first) {
			first = false;
		    } else {
			enumString += ", ";
		    }
		    enumString += b;
		}
		enumString += "),";
		while (++curIndex < index) {
		    enumStrings.add("UNKNOWN" + curIndex + " ()");
		}
		enumStrings.add(enumString);

	    } catch (NumberFormatException ex) {
		log.write("  Skipped\n");
	    }
	}

	for (String s : enumStrings) {
	    out.write(s + "\n");
	}

	in.close();
	out.close();
	log.close();
    }

    static EmbeddedScript getScript(int index) {
	return EmbeddedScript.values()[index];
    }

    public enum EmbeddedScript {

	GetWantBlocking(false),
	GetDistance(true),
	AddItem(true, false, false),
	SetEssential(true, false),
	Rotate(true, false),
	GetLocked(false),
	GetPos(true),
	SetPos(true, false),
	GetAngle(true),
	SetAngle(true, false),
	GetStartingPos(true),
	GetStartingAngle(true),
	GetSecondsPassed(false),
	Activate(true, false),
	GetActorValue(true),
	SetActorValue(true, false),
	ModActorValue(true, false),
	SetAtStart(false),
	GetCurrentTime(false),
	PlayGroup(true, false),
	LoopGroup(true, false, false),
	SkipAnim(false),
	StartCombat(false),
	StopCombat(false),
	GetScale(false),
	IsMoving(false),
	IsTurning(false),
	GetLineOfSight(true),
	AddSpell(true),
	RemoveSpell(true),
	Cast(true, true, true),
	GetButtonPressed(false),
	GetInSameCell(true),
	Enable(false),
	Disable(false),
	GetDisabled(false),
	MenuMode(false),
	PlaceAtMe(true, false, false, false),
	PlaySound(true, false),
	GetDisease(false),
	FailAllObjectives(false),
	GetClothingValue(false),
	SameFaction(false),
	SameRace(false),
	SameSex(false),
	GetDetected(false),
	GetDead(false),
	GetItemCount(true),
	GetGold(false),
	GetSleeping(false),
	GetTalkedToPC(false),
	Say(false, false, true, false, false),
	SayTo(false, false, false, false),
	GetScriptVariable(true, true),
	StartQuest(false),
	StopQuest(false),
	GetQuestRunning(false),
	SetStage(false, true),
	GetStage(false),
	GetStageDone(false, true),
	GetFactionRankDifference(true, false),
	GetAlarmed(false),
	IsRaining(false),
	GetAttacked(false),
	GetIsCreature(false),
	GetLockLevel(false),
	GetShouldAttack(false),
	GetInCell(true),
	GetIsClass(true),
	GetIsRace(true),
	GetIsSex(true),
	GetInFaction(true),
	GetIsID(true),
	GetFactionRank(true),
	GetGlobalValue(true),
	IsSnowing(false),
	FastTravel(true),
	GetRandomPercent(false),
	RemoveMusic(true),
	GetQuestVariable(false, true),
	GetLevel(false),
	IsRotating(false),
	RemoveItem(true, false, false),
	GetLeveledEncounterValue(false),
	GetDeadCount(true),
	AddToMap(true, false),
	StartConversation(true, false, true, true, false, false),
	Drop(true, false),
	AddTopic(false),
	ShowMessage(true),
	SetAlert(false),
	GetIsAlerted(false),
	Look(true, false),
	StopLook(false),
	EvaluatePackage(false),
	SendAssaultAlarm(false, true),
	EnablePlayerControls(false, false, false, false, false, false, false, false, false),
	DisablePlayerControls(false, false, false, false, false, false, false, false, false),
	GetPlayerControlsDisabled(false, false, false, false, false, false, false, false),
	GetHeadingAngle(true),
	PickIdle(false),
	IsWeaponMagicOut(false),
	IsTorchOut(false),
	IsShieldOut(false),
	CreateDetectionEvent(true, false),
	IsActionRef(true),
	IsFacingUp(false),
	GetKnockedState(false),
	GetWeaponAnimType(false),
	IsWeaponSkillType(true),
	GetCurrentAIPackage(false),
	IsWaiting(false),
	IsIdlePlaying(false),
	CompleteQuest(false),
	Lock(false, false),
	UnLock(false),
	IsIntimidatedbyPlayer(false),
	IsPlayerInRegion(true),
	GetActorAggroRadiusViolated(false),
	GetCrimeKnown(true, false, false),
	SetEnemy(true, true, false, false),
	SetAlly(true, true, false, false),
	GetCrime(false, true),
	IsGreetingPlayer(false),
	StartMisterSandMan(false),
	IsGuard(false),
	StartCannibal(false),
	HasBeenEaten(false),
	GetStaminaPercentage(false),
	GetPCIsClass(true),
	GetPCIsRace(true),
	GetPCIsSex(true),
	GetPCInFaction(true),
	SameFactionAsPC(false),
	SameRaceAsPC(false),
	SameSexAsPC(false),
	GetIsReference(true),
	SetFactionRank(true, false),
	ModFactionRank(true, false),
	KillActor(false, false, false),
	ResurrectActor(false),
	IsTalking(false),
	GetWalkSpeed(false),
	GetCurrentAIProcedure(false),
	GetTrespassWarningLevel(false),
	IsTrespassing(false),
	IsInMyOwnedCell(false),
	GetWindSpeed(false),
	GetCurrentWeatherPercent(false),
	GetIsCurrentWeather(true),
	IsContinuingPackagePCNear(false),
	SetCrimeFaction(true),
	GetIsCrimeFaction(true),
	CanHaveFlames(false),
	HasFlames(false),
	AddFlames(false),
	RemoveFlames(false),
	GetOpenState(false),
	MoveToMarker(true, false, false, false),
	GetSitting(false),
	GetFurnitureMarkerID(false),
	GetIsCurrentPackage(true),
	IsCurrentFurnitureRef(true),
	IsCurrentFurnitureObj(true),
	SetSize(false),
	RemoveMe(false),
	DropMe(false),
	GetFactionReaction(true, true),
	SetFactionReaction(true, true, false),
	ModFactionReaction(true, true, false),
	GetDayOfWeek(false),
	IgnoreCrime(false),
	GetTalkedToPCParam(false),
	RemoveAllItems(false, false, false),
	WakeUpPC(false),
	IsPCSleeping(false),
	IsPCAMurderer(false),
	SetCombatStyle(true),
	PlaySound3D(true),
	SelectPlayerSpell(true, true),
	HasSameEditorLocAsRef(true, true),
	HasSameEditorLocAsRefAlias(true, true),
	GetEquipped(true),
	Wait(true),
	StopWaiting(true),
	IsSwimming(false),
	ScriptEffectElapsedSeconds(false),
	SetCellPublicFlag(true, false),
	GetPCSleepHours(false),
	SetPCSleepHours(false),
	GetAmountSoldStolen(false),
	ModAmountSoldStolen(false),
	GetIgnoreCrime(false),
	GetPCExpelled(true),
	SetPCExpelled(true, false),
	GetPCFactionMurder(true),
	SetPCFactionMurder(true, false),
	GetPCEnemyofFaction(true),
	SetPCEnemyofFaction(true, false),
	GetPCFactionAttack(true),
	SetPCFactionAttack(true, false),
	StartScene(true),
	StopScene(true),
	GetDestroyed(false),
	SetDestroyed(false),
	GetActionRef(false),
	GetSelf(false),
	GetContainer(false),
	GetForceRun(false),
	SetForceRun(false),
	GetForceSneak(false),
	SetForceSneak(false),
	AdvancePCSkill(true, false),
	AdvancePCLevel(false),
	HasMagicEffect(true),
	GetDefaultOpen(false),
	SetDefaultOpen(false),
	ShowClassMenu(false),
	ShowRaceMenu(true),
	GetAnimAction(false),
	ShowNameMenu(false),
	SetOpenState(false),
	ResetReference(true),
	IsSpellTarget(true),
	GetVATSMode(false),
	GetPersuasionNumber(false),
	GetVampireFeed(false),
	GetCannibal(false),
	GetIsClassDefault(true),
	GetClassDefaultMatch(false),
	GetInCellParam(true, true),
	UnusedFunction1(false),
	GetCombatTarget(false),
	GetPackageTarget(false),
	ShowSpellMaking(false),
	GetVatsTargetHeight(false),
	SetGhost(false),
	GetIsGhost(false),
	EquipItem(true, false, true),
	UnequipItem(true, false, true),
	SetClass(true),
	SetUnconscious(false),
	GetUnconscious(false),
	SetRestrained(false),
	GetRestrained(false),
	ForceFlee(true, true),
	GetIsUsedItem(true),
	GetIsUsedItemType(true),
	IsScenePlaying(true),
	IsInDialogueWithPlayer(false),
	GetLocationCleared(true),
	SetLocationCleared(true, false),
	ForceRefIntoAlias(true),
	EmptyRefAlias(true),
	GetIsPlayableRace(false),
	GetOffersServicesNow(false),
	GetGameSetting(false),
	StopCombatAlarmOnActor(false),
	HasAssociationType(false, true),
	HasFamilyRelationship(false),
	SetWeather(true, false),
	HasParentRelationship(false),
	IsWarningAbout(true),
	IsWeaponOut(false),
	HasSpell(true),
	IsTimePassing(false),
	IsPleasant(false),
	IsCloudy(false),
	TrapUpdate(false),
	ShowQuestObjectives(false),
	ForceActorValue(true, false),
	IncrementPCSkill(true),
	DoTrap(true, false, false, false, false, false, false, false),
	EnableFastTravel(false),
	IsSmallBump(false),
	GetParentRef(false),
	PlayBink(false, false, false, false, false),
	GetBaseActorValue(true),
	IsOwner(true),
	SetOwnership(true),
	IsCellOwner(true, true),
	SetCellOwnership(true, true),
	IsHorseStolen(false),
	SetCellFullName(true, true),
	SetActorFullName(true),
	IsLeftUp(false),
	IsSneaking(false),
	IsRunning(false),
	GetFriendHit(false),
	IsInCombat(false),
	SetPackDuration(false),
	PlayMagicShaderVisuals(true, false),
	PlayMagicEffectVisuals(true, false),
	StopMagicShaderVisuals(true),
	StopMagicEffectVisuals(true),
	ResetInterior(true),
	IsAnimPlaying(true),
	SetActorAlpha(false, false),
	EnableLinkedPathPoints(false),
	DisableLinkedPathPoints(false),
	IsInInterior(false),
	ForceWeather(true, false),
	ToggleActorsAI(false),
	IsActorsAIOff(false),
	IsWaterObject(false),
	GetPlayerAction(false),
	IsActorUsingATorch(false),
	SetLevel(false, false, false, false),
	ResetFallDamageTimer(false),
	IsXBox(false),
	GetInWorldspace(true),
	ModPCMiscStat(true, false),
	GetPCMiscStat(true),
	GetPairedAnimation(false),
	IsActorAVictim(false),
	GetTotalPersuasionNumber(false),
	SetScale(false),
	ModScale(false),
	GetIdleDoneOnce(false),
	KillAllActors(false),
	GetNoRumors(false),
	SetNoRumors(false),
	Dispel(true),
	GetCombatState(false),
	TriggerHitShader(false),
	GetWithinPackageLocation(true),
	Reset3DState(false),
	IsRidingHorse(false),
	DispelAllSpells(false),
	IsFleeing(false),
	AddAchievement(false),
	DuplicateAllItems(false, false),
	IsInDangerousWater(false),
	EssentialDeathReload(false),
	SetShowQuestItems(false),
	DuplicateNPCStats(false),
	ResetHealth(false),
	SetIgnoreFriendlyHits(false),
	GetIgnoreFriendlyHits(false),
	IsPlayersLastRiddenHorse(false),
	SetActorRefraction(false),
	SetItemValue(false),
	SetRigidBodyMass(false),
	ShowViewerStrings(false),
	ReleaseWeatherOverride(false),
	SetAllReachable(false),
	SetAllVisible(false),
	SetNoAvoidance(false),
	SendTrespassAlarm(false),
	SetSceneIsComplex(false),
	Autosave(false),
	StartMasterFileSeekData(false),
	DumpMasterFileSeekData(false),
	IsActor(false),
	IsEssential(false),
	PreloadMagicEffect(true),
	ShowDialogSubtitles(false),
	SetPlayerResistingArrest(false),
	IsPlayerMovingIntoNewSpace(false),
	GetInCurrentLoc(true),
	GetInCurrentLocAlias(true),
	GetTimeDead(false),
	HasLinkedRef(true),
	GetLinkedRef(true),
	DamageObject(false),
	IsChild(false),
	GetStolenItemValueNoCrime(true),
	GetLastPlayerAction(false),
	IsPlayerActionActive(false),
	SetTalkingActivatorActor(false),
	IsTalkingActivatorActor(false),
	ShowBarterMenu(false),
	IsInList(true),
	GetStolenItemValue(true),
	AddPerk(true),
	GetCrimeGoldViolent(true),
	GetCrimeGoldNonviolent(true),
	ShowRepairMenu(false),
	HasShout(true),
	AddNote(true),
	RemoveNote(true),
	GetHasNote(true),
	AddToFaction(true, false),
	RemoveFromFaction(true),
	DamageActorValue(true, false),
	RestoreActorValue(true, false),
	TriggerHUDShudder(false, false, false, false),
	GetObjectiveFailed(false, false),
	SetObjectiveFailed(false, false, false),
	SetGlobalTimeMultiplier(false),
	GetHitLocation(false),
	IsPC1stPerson(false),
	PurgeCellBuffers(false),
	PushActorAway(true, false),
	SetActorsAI(false),
	ClearOwnership(false),
	GetCauseofDeath(false),
	IsLimbGone(false),
	IsWeaponInList(true),
	PlayIdle(false),
	ApplyImageSpaceModifier(true, false),
	RemoveImageSpaceModifier(true, false),
	IsBribedbyPlayer(false),
	GetRelationshipRank(false),
	SetRelationshipRank(false, false),
	SetCellImageSpace(true, true),
	ShowChargenMenu(false),
	GetVATSValue(false, false),
	IsKiller(false),
	IsKillerObject(true),
	GetFactionCombatReaction(true, true),
	UseWeapon(true, true, true, false, false, false, false, false, true),
	EvaluateSpellConditions(false),
	ToggleMotionBlur(false),
	Exists(true),
	GetGroupMemberCount(false),
	GetGroupTargetCount(false),
	SetObjectiveCompleted(false, false, false),
	SetObjectiveDisplayed(false, false, false),
	GetObjectiveCompleted(false, false),
	GetObjectiveDisplayed(false, false),
	SetImageSpace(true),
	PipboyRadio(false, true),
	RemovePerk(true),
	DisableAllActors(false),
	GetIsFormType(false),
	GetIsVoiceType(true),
	GetPlantedExplosive(false),
	CompleteAllObjectives(false),
	IsScenePackageRunning(false),
	GetHealthPercentage(false),
	SetAudioMultithreading(false),
	GetIsObjectType(true),
	ShowChargenMenuParams(false, false, false),
	GetDialogueEmotion(false),
	GetDialogueEmotionValue(false),
	ExitGame(false),
	GetIsCreatureType(false),
	PlayerCreatePotion(true, true, true),
	PlayerEnchantObject(true, true, true),
	ShowWarning(false),
	EnterTrigger(true),
	MarkForDelete(false),
	SetPlayerAIDriven(false),
	GetInCurrentLocFormList(true),
	GetInZone(true),
	GetVelocity(true),
	GetGraphVariableFloat(false),
	HasPerk(true),
	GetFactionRelation(false),
	IsLastIdlePlayed(true),
	SetNPCRadio(false, true),
	SetPlayerTeammate(false),
	GetPlayerTeammate(false),
	GetPlayerTeammateCount(false),
	OpenActorContainer(false),
	ClearFactionPlayerEnemyFlag(true),
	ClearActorsFactionsPlayerEnemyFlag(false),
	GetActorCrimePlayerEnemy(false),
	GetCrimeGold(true),
	SetCrimeGold(false, true),
	ModCrimeGold(false, false, true),
	GetPlayerGrabbedRef(false),
	IsPlayerGrabbedRef(true),
	PlaceLeveledActorAtMe(true, false, true),
	GetKeywordItemCount(true),
	ShowLockpickMenu(false),
	GetBroadcastState(false),
	SetBroadcastState(false),
	StartRadioConversation(false),
	GetDestructionStage(false),
	ClearDestruction(false),
	CastImmediateOnSelf(true),
	GetIsAlignment(true),
	ResetQuest(false),
	SetQuestDelay(false, false),
	IsProtected(false),
	GetThreatRatio(false),
	MatchFaceGeometry(false, false),
	GetIsUsedItemEquipType(true),
	GetPlayerName(false),
	FireWeapon(true),
	PayCrimeGold(false, false, true),
	UnusedFunction2(false),
	MatchRace(false),
	SetPCYoung(false),
	SexChange(true, false),
	IsCarryable(false),
	GetConcussed(false),
	SetZoneRespawns(true, false),
	SetVATSTarget(false),
	GetMapMarkerVisible(false),
	ResetInventory(false),
	PlayerKnows(true),
	GetPermanentActorValue(true),
	GetKillingBlowLimb(false),
	GoToJail(true, false, false),
	CanPayCrimeGold(true),
	ServeTime(false),
	GetDaysInJail(false),
	EPAlchemyGetMakingPoison(false),
	EPAlchemyEffectHasKeyword(true),
	ShowAllMapMarkers(false, false, false),
	GetAllowWorldInteractions(false),
	ResetAI(false),
	SetRumble(false, false, false),
	SetNoActivationSound(true),
	ClearNoActivationSound(false),
	GetLastHitCritical(false),
	AddMusic(true),
	UnusedFunction3(false),
	UnusedFunction4(false),
	SetPCToddler(false),
	IsCombatTarget(false),
	TriggerScreenBlood(false),
	GetVATSRightAreaFree(true),
	GetVATSLeftAreaFree(true),
	GetVATSBackAreaFree(true),
	GetVATSFrontAreaFree(true),
	GetIsLockBroken(false),
	IsPS3(false),
	IsWin32(false),
	GetVATSRightTargetVisible(true),
	GetVATSLeftTargetVisible(true),
	GetVATSBackTargetVisible(true),
	GetVATSFrontTargetVisible(true),
	AttachAshPile(false),
	SetCriticalStage(true),
	IsInCriticalStage(true),
	RemoveFromAllFactions(false),
	GetXPForNextLevel(false),
	ShowLockpickMenuDebug(false),
	ForceSave(false),
	GetInfamy(true),
	GetInfamyViolent(true),
	GetInfamyNonViolent(true),
	UnusedFunction5(false),
	Sin(false, false),
	Cos(false, false),
	Tan(false, false),
	Sqrt(false),
	Log(false, false),
	Abs(false),
	GetQuestCompleted(false),
	UnusedFunction6(false),
	PipBoyRadioOff(false),
	AutoDisplayObjectives(false),
	IsGoreDisabled(false),
	FadeSFX(false),
	SetMinimalUse(false),
	IsSceneActionComplete(true, false),
	ShowQuestStages(false),
	GetSpellUsageNum(true),
	ForceRadioStationUpdate(false),
	GetActorsInHigh(false),
	HasLoaded3D(false),
	DisableAllMines(false),
	SetLastExtDoorActivated(true),
	KillQuestUpdates(false),
	IsImageSpaceActive(true),
	HasKeyword(true),
	HasRefType(true),
	LocationHasKeyword(true),
	LocationHasRefType(true),
	CreateEvent(true, true, true, true, false, false),
	GetIsEditorLocation(true),
	GetIsAliasRef(true),
	GetIsEditorLocAlias(true),
	IsSprinting(false),
	IsBlocking(false),
	HasEquippedSpell(true),
	GetCurrentCastingType(true),
	GetCurrentDeliveryType(true),
	EquipSpell(true, true),
	GetAttackState(false),
	GetAliasedRef(true),
	GetEventData(true, true, true),
	IsCloserToAThanB(true, true),
	EquipShout(true),
	GetEquippedShout(true),
	IsBleedingOut(false),
	UnlockWord(true),
	TeachWord(true),
	AddToContainer(true, false),
	GetRelativeAngle(true, true),
	SendAnimEvent(false),
	Shout(true, false, true),
	AddShout(true),
	RemoveShout(true),
	GetMovementDirection(false),
	IsInScene(false),
	GetRefTypeDeadCount(true, true),
	GetRefTypeAliveCount(true, true),
	ApplyHavokImpulse(false, false, false, false),
	GetIsFlying(false),
	IsCurrentSpell(true, true),
	SpellHasKeyword(true, true),
	GetEquippedItemType(true),
	GetLocationAliasCleared(true),
	SetLocationAliasCleared(true),
	GetLocAliasRefTypeDeadCount(true, true),
	GetLocAliasRefTypeAliveCount(true, true),
	IsWardState(true),
	IsInSameCurrentLocAsRef(true, true),
	IsInSameCurrentLocAsRefAlias(true, true),
	LocAliasIsLocation(true, true),
	GetKeywordDataForLocation(true, true),
	SetKeywordDataForLocation(true, true, false),
	GetKeywordDataForAlias(true, true),
	SetKeywordDataForAlias(true, true, false),
	LocAliasHasKeyword(true, true),
	IsNullPackageData(true),
	GetNumericPackageData(true),
	IsFurnitureAnimType(true),
	IsFurnitureEntryType(true),
	GetHighestRelationshipRank(false),
	GetLowestRelationshipRank(false),
	HasAssociationTypeAny(true),
	HasFamilyRelationshipAny(false),
	GetPathingTargetOffset(true),
	GetPathingTargetAngleOffset(true),
	GetPathingTargetSpeed(false),
	GetPathingTargetSpeedAngle(true),
	GetMovementSpeed(false),
	GetInContainer(true),
	IsLocationLoaded(true),
	IsLocAliasLoaded(true),
	IsDualCasting(false),
	DualCast(true, true),
	GetVMQuestVariable(false, true),
	GetVMScriptVariable(true, true),
	IsEnteringInteractionQuick(false),
	IsCasting(false),
	GetFlyingState(false),
	SetFavorState(false),
	IsInFavorState(false),
	HasTwoHandedWeaponEquipped(false),
	IsExitingInstant(false),
	IsInFriendStatewithPlayer(false),
	GetWithinDistance(true, false),
	GetActorValuePercent(true),
	IsUnique(false),
	GetLastBumpDirection(false),
	CameraShake(false, false),
	IsInFurnitureState(true),
	GetIsInjured(false),
	GetIsCrashLandRequest(false),
	GetIsHastyLandRequest(false),
	UpdateQuestInstanceGlobal(false, true),
	SetAllowFlying(false),
	IsLinkedTo(true, true),
	GetKeywordDataForCurrentLocation(true),
	GetInSharedCrimeFaction(true),
	GetBribeAmount(false),
	GetBribeSuccess(false),
	GetIntimidateSuccess(false),
	GetArrestedState(false),
	GetArrestingActor(false),
	ClearArrestState(false),
	EPTemperingItemIsEnchanted(false),
	EPTemperingItemHasKeyword(true),
	GetReceivedGiftValue(false),
	GetGiftGivenValue(false),
	ForceLocIntoAlias(true, true),
	GetReplacedItemType(true),
	SetHorseActor(true),
	PlayReferenceEffect(true, false, true),
	StopReferenceEffect(true),
	PlayShaderParticleGeometry(true, false),
	StopShaderParticleGeometry(true, false),
	ApplyImageSpaceModifierCrossFade(true, false),
	RemoveImageSpaceModifierCrossFade(false),
	IsAttacking(false),
	IsPowerAttacking(false),
	IsLastHostileActor(false),
	GetGraphVariableInt(false),
	GetCurrentShoutVariation(false),
	PlayImpactEffect(false, false, false, false, false, false, false, false),
	ShouldAttackKill(false),
	SendStealAlarm(false),
	GetActivationHeight(false),
	EPModSkillUsage_IsAdvanceSkill(true),
	WornHasKeyword(true),
	GetPathingCurrentSpeed(false),
	GetPathingCurrentSpeedAngle(true),
	KnockAreaEffect(false, false),
	InterruptCast(false),
	AddFormToFormList(true, true),
	RevertFormList(true),
	AddFormToLeveledList(true, true, false, false),
	RevertLeveledList(true),
	EPModSkillUsage_AdvanceObjectHasKeyword(true),
	EPModSkillUsage_IsAdvanceAction(true),
	EPMagic_SpellHasKeyword(true),
	GetNoBleedoutRecovery(false),
	SetNoBleedoutRecovery(false),
	EPMagic_SpellHasSkill(true),
	IsAttackType(true),
	IsAllowedToFly(false),
	HasMagicEffectKeyword(true),
	IsCommandedActor(false),
	IsStaggered(false),
	IsRecoiling(false),
	IsExitingInteractionQuick(false),
	IsPathing(false),
	GetShouldHelp(false),
	HasBoundWeaponEquipped(true),
	GetCombatTargetHasKeyword(true),
	UpdateLevel(false),
	GetCombatGroupMemberCount(false),
	IsIgnoringCombat(false),
	GetLightLevel(false),
	SavePCFace(false),
	SpellHasCastingPerk(true),
	IsBeingRidden(false),
	IsUndead(false),
	GetRealHoursPassed(false),
	UnequipAll(false),
	IsUnlockedDoor(false),
	IsHostileToActor(false),
	GetTargetHeight(true),
	IsPoison(false),
	WornApparelHasKeywordCount(true),
	GetItemHealthPercent(false),
	EffectWasDualCast(false),
	GetKnockStateEnum(false),
	DoesNotExist(false);

	Boolean[] paramsFormMask;

	EmbeddedScript(Boolean... params) {
	    this.paramsFormMask = params;
	}

	boolean isForm(int paramIndex) {
	    if (paramsFormMask.length > paramIndex && paramsFormMask[paramIndex]) {
		return true;
	    } else {
		return false;
	    }
	}
    }
}
